// Generates test/parity/embedded_fixtures.dart from the canonical parity
// fixtures.
//
// The web-platform parity suite cannot read fixture files at runtime (dart2js
// has no dart:io), so the slice of fixtures it needs is embedded as Dart
// constants. This tool copies them verbatim from tests/fixtures/parity so the
// fixtures stay the single source of truth; CI regenerates and diffs the
// output, so the embedded copy can never drift.
//
// Run from the package root: `dart run tool/generate_web_fixtures.dart`.

import 'dart:convert';
import 'dart:io';

void main() {
  // tool/ -> core/ -> dart/ -> src/ -> monorepo root, then tests/fixtures.
  final fixtures =
      Platform.script.resolve('../../../../tests/fixtures/parity/');

  String read(String relative) =>
      File.fromUri(fixtures.resolve(relative)).readAsStringSync().trimRight();

  final entries = <String, String>{
    'numbersJson': read('numbers.json'),
    'fnv1aJson': read('fnv1a.json'),
    'mulberry32Json': read('mulberry32.json'),
    'glassStyle': read('styles/glass.json'),
    'glassAvatars': read('avatars/glass.json'),
  };

  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/generate_web_fixtures.dart — do not edit '
        'by hand.')
    ..writeln('//')
    ..writeln('// A verbatim copy of the parity fixtures the web-platform '
        'suite needs,')
    ..writeln('// embedded as constants because dart2js cannot read files at '
        'runtime.')
    ..writeln('// Regenerate with `dart run tool/generate_web_fixtures.dart` '
        'whenever the')
    ..writeln('// fixtures change; CI regenerates and diffs this file, so it '
        'cannot drift.')
    ..writeln('library;')
    ..writeln();

  for (final entry in entries.entries) {
    buffer
      ..writeln('const String ${entry.key} = ${_dartLiteral(entry.value)};')
      ..writeln();
  }

  final out = Platform.script.resolve('../test/parity/embedded_fixtures.dart');
  File.fromUri(out).writeAsStringSync(buffer.toString());

  stdout.writeln('Wrote ${out.toFilePath()}');
}

/// Renders [value] as a Dart double-quoted string literal. JSON string
/// escaping is a subset of Dart's, except `$` (Dart interpolation) and the
/// U+2028/U+2029 line separators (legal in a JSON string but a line break in
/// Dart source), which are escaped explicitly.
String _dartLiteral(String value) => jsonEncode(value)
    .replaceAll(r'$', r'\$')
    .replaceAll('\u{2028}', '\\u{2028}')
    .replaceAll('\u{2029}', '\\u{2029}');
