name: Split PHP Core

on:
  push:
    branches:
      - '*.x'
    tags:
      - 'v*'

jobs:
  split:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: danharrin/monorepo-split-github-action@v2.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.SPLIT_TOKEN }}
        with:
          package_directory: src/php/core
          repository_organization: dicebear
          repository_name: php-core
          branch: ${{ github.ref_name }}
          user_name: dicebear-bot
          user_email: bot@dicebear.com
